# WhatATheme
markdown: kramdown

# URL of the Site
url: 'zoe-elena.com'
# Base URL of the Site (i.e., Name of the Repository in which the Site is hosted)
baseurl: 

# Title of the Site
title: Zoe Elena
# Description of the Site
description: Singer-songwriter, Musician, Poet
# URL of Image of the Site
site-image: /WhatATheme/assets/images/meta.jpg
# Keywords of the Site
site-keywords: Ukelele, Sing, Singer-songwriter, songwriter, violin, guitar, vocal, independent artist, recording artist
# URL for the Image of custom Favicon
favicon-url: 

# URL of the Image of Custom Hero Image (i.e., the image in the background of the very first section of the Homepage)
heroimage: https://images.pexels.com/photos/220444/pexels-photo-220444.jpeg?auto=compress&cs=tinysrgb&dpr=2&h=650&w=940

# Social Media and Contact
# If you don't want to use any icon, you can leave them blank.
email: zoenordquist@gmail.com
facebook_username: ZowayHern
twitter_username:
instagram_username: just_zoeeelena
linkedin_username:
github_username:
youtube_channel_id: UCnk4MFARN60heix6DMgd-BA
reddit_username: 
behance_username: 
dribbble_username:
spotify_username:

# Google Analytics
google-analytics: 

# Disqus
disqus-shortname: 

# Name of the Author
author-name: Zoe Elena
# URL for the Image of the Author
author-image: assets/images/zoe-bw.jpg
# 60 Words About the Author
author-about: Hi, I'm Zoe Elena. Here is what you need to know about me
author-about2: # this is the second about text, below the buttons
# URL to the Author's Profile (i.e., Github, Twitter, Stackoverflow, etc)
author-url: 

# SASS
sass:
  sass_dir: _sass
  style: compressed

# Build settings
plugins:
  - jekyll-admin
  - jekyll-feed

# Permalink
permalink: "blog/:title"

# Compress
compress_html:
  clippings: all

# Defaults
defaults:
  -
    scope:
      type: 'posts'
    values:
      layout: post
      post-image: ""
      description: ""
      tags:
        - ""
  -
    scope:
      type: 'pages'
    values:
      layout: page

# Exclude
exclude:
  - .sass-cache/
  - .jekyll-cache/
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - node_modules/
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
